### ISSUE TITLE
SceneLabels don't work with newlines (\n)

### ISSUE THREAD

**Issue by DaZombieKiller** [ivansafrin/Polycode#652]
When using the newline escape character in a SceneLabel, I get the following:
http://puu.sh/j9UQz/16b2bcca4b.png

**Comment by fodinabor** [comment]
I think SceneLabels are not able to be multi-lined. You would have to use an UIMultilineLabel (which creates several UILabels..)

**Comment by DaZombieKiller** [comment]
So I tried that, and it crashed.

    local label = UIMultilineLabel("Multiline\ntest", 24)
	label:setAnchorPoint(Vector3(-1, -1, 0))
	label:setPosition(70, 380)
	self.hudScene:addChild(label)

**Comment by fodinabor** [comment]
Are you working on Windows or Linux? Then you might have to copy [UIThemes.pak](https://github.com/ivansafrin/Polycode/blob/master/Assets/UIThemes.pak?raw=true) to IDE/Standalone/Player, IDE/Standalone/Publish/Win and IDE/Standalone/Publish/Linux..
That is an know issue in 0.8.4 that is already fixed in latest master.

**Comment by DaZombieKiller** [comment]
I'm working on Windows, and even after doing that, it still crashed.

    Error in file UI/UIMultilineLabel.lua on line 27
    bad argument #3 to 'UIMultilineLabel' (number expected, got string)
    Backtrace:
    In file UI/UIMultilineLabel.lua on line 27
    File not available.

**Comment by fodinabor** [comment]
`UIMultilineLabel (text , size , spacing , fontName , amode )`
you have to specify a spacing aswell - the space between the lines

**Comment by DaZombieKiller** [comment]
I changed the line to read

    label = UIMultilineLabel("Multiline\ntest", 24, 24)

It no longer crashes, but nothing shows up.

**Comment by fodinabor** [comment]
do any of these code examples work:
http://polycode.org/learn/ui

**Comment by DaZombieKiller** [comment]
They compile, but nothing appears onscreen

**Comment by fodinabor** [comment]
What happens if you add this to the beginning of the file:
`Services.Config:setStringValue("Polycode","uiDefaultFontColor", "0xffffffff")`

**Comment by DaZombieKiller** [comment]
...wow, I feel so stupid now. That fixed it. To think, the problem was font colour

**Comment by fodinabor** [comment]
well.. the problem is that it actually should be automatically loaded by the player when the UIThemes.pak is in the same directory... so you normally shouldn't have to do that..
When I find time I'll have a closer look at that issue.. (once again :confused:)
